# Generated by Django 3.0 on 2019-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_content', models.TextField()),
                ('service_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
