# Generated by Django 3.0 on 2019-12-03 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191203_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 22, 36, 52, 583583), verbose_name='date published'),
        ),
    ]
