# Generated by Django 3.0 on 2019-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191203_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_published',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
